import { createContext } from "react"

export default createContext({
  isAdmin: false,
  isOpen: true,
  isVisible: false,
  handleAdd: () => {},
  handleDelete: () => {},
  handleGenerate: () => {},
  products: [],
  activeTab: "",
  existingProduct: {},
  handleEdit: () => {},
  inputRef: {},
  newProduct: {},
  setIsVisible: () => {},
  setNewProduct: () => {},
  setExistingProduct: async () => {},
  setIsOpen: async () => {},
  setActiveTab: async () => {},
  selectedCardId: null,
  setSelectedCardId: async () => {},
  setIsAdmin: () => {},
  basketProducts: [],
  quantity: 0,
  setQuantity: () => {},
  total: 0,
  handleDeleteBasketProduct: () => {},
  // handleIncrementationBasketProduct: () => {},
  // ammount: 0,
})
